spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    username: ${USER_NAME:URMS_CADASTRO}
    password: ${USER_PASS:cad#2020}
    url: ${DATABASE_URI:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=RTPRBR70_DB)(PORT=1941)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=RTPRBR70)))}
    driver-class-name: oracle.jdbc.OracleDriver

app:
  params:
    flexfieldUri: ${FLEX_FILD_URI:http://ws-flexfield-company-products.apps.ocpvp1.company.com.br/flexfield}

logging:
  level:
    root: INFO

server:
  servlet:
    contextPath: /items
  port: 8082

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"
